"""Paths, environment settings and defaults for the LHASA API server.

All values can be overridden with environment variables so the server can be
deployed next to a LHASA checkout that lives somewhere else.
"""
from __future__ import annotations

import os
from pathlib import Path

# backend/app/config.py -> backend/ -> repository root
BACKEND_DIR = Path(__file__).resolve().parents[1]
REPO_ROOT = Path(__file__).resolve().parents[2]

# The trimmed NASA LHASA checkout (lhasa.py + model.json + lhasa.yml).
LHASA_DIR = Path(os.environ.get("LHASA_DIR", str(REPO_ROOT / "LHASA"))).resolve()

# Where lhasa.py writes nrt/ and fcast/ outputs (default: next to the model).
LHASA_OUTPUT_DIR = Path(
    os.environ.get("LHASA_OUTPUT_DIR", str(LHASA_DIR))
).resolve()

# Interpreter used to launch lhasa.py. When the `lhasa` conda env is active,
# plain "python" is correct.
PYTHON_BIN = os.environ.get("LHASA_PYTHON", "python")

# When live NASA data is not configured (no Earthdata creds / no static data),
# the API scores the real trained model with sample inputs instead of failing.
# Set LHASA_DEMO=0 to disable and require real LHASA runs.
DEMO_ENABLED = os.environ.get("LHASA_DEMO", "1").strip().lower() not in {
    "0",
    "false",
    "no",
    "off",
}

MODEL_FILE = LHASA_DIR / "model.json"
STATIC_DIR = LHASA_DIR / "static"

# Files that must exist in LHASA/static before a nowcast can run. They come
# from static.zip (https://gpm.nasa.gov/sites/default/files/data/landslides/static.zip)
REQUIRED_STATIC_FILES = [
    "pga.nc4",
    "Lithology.nc4",
    "Slope.nc4",
    "mask.nc4",
    "p99.nc4",
]

# Additional file only needed when forecast days are requested (lead > 0).
FORECAST_STATIC_FILES = ["p99geos.nc4"]

# North Eastern Region (India) study area used by the frontend monitoring
# districts. LHASA is global, so every run is cropped to this bounding box.
# Covers Arunachal/Sikkim (north) through Tripura/Mizoram (south).
DEFAULT_BBOX = {"north": 29.5, "south": 21.5, "east": 97.5, "west": 87.8}

# Forecast days generated by default. The frontend shows 24h/48h/72h cards.
DEFAULT_LEAD_DAYS = 3

# Where run metadata is persisted between restarts.
RUNS_STATE_FILE = BACKEND_DIR / ".lhasa_runs" / "runs.json"

MAX_LOG_CHARS = 12_000
