"""SQLAlchemy models for the monitoring platform's persisted data."""
from __future__ import annotations

from datetime import datetime, timezone

from sqlalchemy import DateTime, Float, Integer, String, Text
from sqlalchemy.orm import Mapped, mapped_column

from .db import Base


def _utcnow() -> datetime:
    return datetime.now(timezone.utc)


class ZoneInput(Base):
    """Latest live inputs (rain mm / wetness 0-1) for a monitored zone.

    Written by sensor aggregation or the IMD weather feed; read by the model
    scorer, which falls back to calibrated sample params when absent.
    """

    __tablename__ = "zone_inputs"

    zone_id: Mapped[str] = mapped_column(String(16), primary_key=True)
    rain_mm: Mapped[float | None] = mapped_column(Float, nullable=True)
    wetness: Mapped[float | None] = mapped_column(Float, nullable=True)
    source: Mapped[str] = mapped_column(String(64), default="sensor")
    recorded_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=_utcnow)


class SensorReading(Base):
    """A single telemetry push from an IoT sensor (rain / moisture / tilt)."""

    __tablename__ = "sensor_readings"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    sensor_id: Mapped[str] = mapped_column(String(32), index=True)
    zone_id: Mapped[str] = mapped_column(String(16), index=True)
    sensor_type: Mapped[str] = mapped_column(String(32))
    value: Mapped[float] = mapped_column(Float)
    unit: Mapped[str] = mapped_column(String(16), default="")
    recorded_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=_utcnow, index=True
    )


class CitizenReport(Base):
    """Geo-tagged citizen / field-official report (cracks, blockages, slides)."""

    __tablename__ = "citizen_reports"

    id: Mapped[str] = mapped_column(String(32), primary_key=True)
    reporter_name: Mapped[str] = mapped_column(String(128), default="")
    reporter_phone: Mapped[str | None] = mapped_column(String(32), nullable=True)
    incident_type: Mapped[str] = mapped_column(String(32))
    district: Mapped[str] = mapped_column(String(64), index=True)
    state: Mapped[str] = mapped_column(String(64), default="")
    description: Mapped[str] = mapped_column(Text, default="")
    latitude: Mapped[float] = mapped_column(Float)
    longitude: Mapped[float] = mapped_column(Float)
    status: Mapped[str] = mapped_column(String(24), default="pending", index=True)
    media_urls: Mapped[str] = mapped_column(Text, default="[]")  # JSON list
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=_utcnow)
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=_utcnow, onupdate=_utcnow
    )


class AlertRecord(Base):
    """Raised alerts (auto-generated by the evaluate engine or manually)."""

    __tablename__ = "alerts"

    id: Mapped[str] = mapped_column(String(32), primary_key=True)
    title: Mapped[str] = mapped_column(String(200))
    message: Mapped[str] = mapped_column(Text, default="")
    severity: Mapped[str] = mapped_column(String(24), index=True)
    district: Mapped[str] = mapped_column(String(64), index=True)
    state: Mapped[str] = mapped_column(String(64), default="")
    zone_id: Mapped[str | None] = mapped_column(String(16), nullable=True)
    status: Mapped[str] = mapped_column(String(24), default="active", index=True)
    source: Mapped[str] = mapped_column(String(64), default="ML Engine")
    translations: Mapped[str] = mapped_column(Text, default="{}")  # JSON {lang: {title, message}}
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=_utcnow)
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=_utcnow, onupdate=_utcnow
    )
